MyBlog/Controllers/PostController.cs
using MyBlog.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class PostController : Controller
    {
        DbMyBlogEntities db = new DbMyBlogEntities();
        public List<SelectListItem> makeTagList()
        {
            List<SelectListItem> dropdownItems = (from item in db.tbl_tag.ToList()
                                                  select new SelectListItem
                                                  {
                                                      Text = item.name,
                                                      Value = item.id.ToString()
                                                  }
                                                 ).ToList();
            return dropdownItems;
        }
        public List<SelectListItem> makeUserList()
        {
            List<SelectListItem> dropdownItems = (from item in db.tbl_user.ToList()
                                                  select new SelectListItem
                                                  {
                                                      Text = item.username,
                                                      Value = item.id.ToString()
                                                  }
                                                 ).ToList();
            return dropdownItems;
        }

        // GET: Post
        public ActionResult Index(string searched)
        {
            
            var posts = from post in db.tbl_post.ToList() select post;
            if (!String.IsNullOrEmpty(searched))
            {
                posts = posts.Where(post => post.blog_content.Contains(searched) || post.title.Contains(searched));
            }
            return View(posts.ToList());
        }
        public ActionResult DeletePost(int id)
        {
            var post = db.tbl_post.Find(id);
            db.tbl_post.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult AddPost()
        {
            ViewBag.dropdownItemsTag = makeTagList();
            ViewBag.dropdownItemsUser = makeUserList();
            return View();
        }
        [HttpPost]
        public ActionResult AddPost(tbl_post post)
        {
            var tags = db.tbl_tag.Where(m => m.id == post.tbl_tag.id).FirstOrDefault();
            var users = db.tbl_user.Where(m => m.id == post.tbl_user.id).FirstOrDefault();
            post.tbl_tag = tags;
            post.tbl_user = users;
            post.create_time = DateTime.Now;
            db.tbl_post.Add(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BringPostForUpdate(int id)
        {
            ViewBag.dropdownItemsTag = makeTagList();
            ViewBag.dropdownItemsUser = makeUserList();
            return View(db.tbl_post.Find(id));
        }
        public ActionResult UpdatePost(tbl_post p)
        {
            var reelPost = db.tbl_post.Find(p.id);
            var tags = db.tbl_tag.Where(m => m.id == p.tbl_tag.id).FirstOrDefault();
            var users = db.tbl_user.Where(m => m.id == p.tbl_user.id).FirstOrDefault();
            reelPost.tbl_user = users;
            reelPost.tbl_tag = tags;
            reelPost.title = p.title;
            reelPost.blog_content = p.blog_content;
            reelPost.update_time = DateTime.Now;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

MyBlog/Views/Post/AddPost.cshtml
@model MyBlog.Models.Entity.tbl_post
@{
    ViewBag.Title = "AddPost";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

    <form class="form-group" method="post">
        <label>Title</label>
        @Html.TextBoxFor(m => m.title, new { @class = "form-control" })
        <label>Content</label>
        @Html.TextAreaFor(m => m.blog_content, new { @class = "form-control" })
        <label>Tags</label>
        @Html.DropDownListFor(m => m.tbl_tag.id, (List<SelectListItem>)ViewBag.dropdownItemsTag, new { @class = "form-control" })
        <label>Users</label>
        @Html.DropDownListFor(m => m.tbl_user.id, (List<SelectListItem>)ViewBag.dropdownItemsUser, new { @class = "form-control" })
        <button class="btn btn-info" style="margin-top:5px;">Ekle</button>
    </form>

MyBlog/Views/Post/BringPostForUpdate.cshtml
@model MyBlog.Models.Entity.tbl_post
@{
    ViewBag.Title = "BringPostForUpdate";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

@using (Html.BeginForm("UpdatePost", "Post", FormMethod.Post))
{
    @Html.HiddenFor(m=>m.create_time)
    @Html.HiddenFor(m => m.id)
    <label>Title</label>
    @Html.TextBoxFor(m => m.title, new { @class = "form-control" })
    <label>Content</label>
    @Html.TextAreaFor(m => m.blog_content, new { @class = "form-control" })
    <label>Tags</label>
    @Html.DropDownListFor(m => m.tbl_tag.id, (List<SelectListItem>)ViewBag.dropdownItemsTag, new { @class = "form-control" })
    <label>Author</label>
    @Html.DropDownListFor(m => m.tbl_user.id, (List<SelectListItem>)ViewBag.dropdownItemsUser, new { @class = "form-control" })
   


    <input type="submit" value="Update" style="margin-top:10px; float:right;" />

}

MyBlog/Views/Post/Index.cshtml
@using MyBlog.Models.Entity
@model List<tbl_post>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}


@using (Html.BeginForm("Index", "Post", FormMethod.Get))
{
    <div style="float:right; margin:10px;">
        @Html.TextBox("searched")
        
        <input type="submit" value="Ara" />
    </div>
}
<table class="table table-bordered" style="margin:5px 0px 0px 0px;">
    <tr>
        <th>
            Post ID
        </th>
        <th>Title</th>
        <th>Content</th>
        <th>Tags</th>
        <th>Create Time</th>
        <th>Update Time</th>
        <th>Author Name</th>
        <th>Delete</th>
        <th>Update</th>

    </tr>
    @foreach(var post in Model)
    {
        <tr>
            <td>@post.id</td>
            <td>@post.title</td>
            <td>@post.blog_content</td>
            <td>@post.tbl_tag.name</td>
            <td>@post.create_time</td>
            <td>@post.update_time</td>
            <td>@post.tbl_user.username</td>
            @*Burada actionResult ile alert dialogta cıkarılabilir postu silerken.*@
            <td><a href="/Post/DeletePost/@post.id" class="btn btn-danger">Delete</a></td>
            <td><a href="/Post/BringPostForUpdate/@post.id" class="btn btn-primary">Update</a></td>
        </tr>
    }
    
</table>
<a href="/Post/AddPost" class="btn btn-info" style="margin-top:10px; float:right;">Add New Post</a>