MyBlog/Controllers/TagController.cs
using MyBlog.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyBlog.Controllers
{
    public class TagController : Controller
    {
        DbMyBlogEntities db = new DbMyBlogEntities();
        // GET: Tag
        public ActionResult Index()
        {

            var values = db.tbl_tag.ToList();
            return View(values);
        }
        public ActionResult DeleteTag(int id)
        {
            var tag = db.tbl_tag.Find(id);
            db.tbl_tag.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult AddTag()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult AddTag(tbl_tag tag)
        {
            db.tbl_tag.Add(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult BringTagForUpdate(int id)
        {
            return View(db.tbl_tag.Find(id));
        }
        public ActionResult UpdateTag(tbl_tag t)
        {
            var tag = db.tbl_tag.Find(t.id);
            tag.name = t.name;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MyBlog/Views/Tag/AddTag.cshtml
@model MyBlog.Models.Entity.tbl_tag
@{
    ViewBag.Title = "AddTag";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

<form class="form-group" method="post">
    <label>Tag Name</label>
    @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
   
    <button class="btn btn-info" style="margin-top:5px;">Ekle</button>
</form>

MyBlog/Views/Tag/BringTagForUpdate.cshtml
@model MyBlog.Models.Entity.tbl_tag
@{
    ViewBag.Title = "BringTagForUpdate";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}

@using (Html.BeginForm("UpdateTag", "Tag", FormMethod.Post))
{
   
    @Html.HiddenFor(m => m.id)
    <label>Tag Name</label>
    @Html.TextBoxFor(m => m.name, new { @class = "form-control" })
    <input type="submit" value="Update" style="margin-top:10px; float:right;" />

}

MyBlog/Views/Tag/Index.cshtml
@using MyBlog.Models.Entity
@model List<tbl_tag>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MainLayout.cshtml";
}


<table class="table table-bordered" style="margin:5px 0px 0px 0px;">
    <tr>
        <th>
            Tag ID
        </th>
        <th>Name</th>
        <th>Delete</th>
        <th>Update</th>

    </tr>
    @foreach (var tag in Model)
    {
        <tr>
            <td>@tag.id</td>
            <td>@tag.name</td>
            
            @*Burada actionResult ile alert dialogta cıkarılabilir postu silerken.*@
            <td><a href="/Tag/DeleteTag/@tag.id" class="btn btn-danger">Delete</a></td>
            <td><a href="/Tag/BringTagForUpdate/@tag.id" class="btn btn-primary">Update</a></td>
        </tr>
    }

</table>
<a href="/Tag/AddTag" class="btn btn-info" style="margin-top:10px; float:right;">Add New Tag</a>